name = str(input("Enter your Name: "))
sid = str(input("Enter your SID: "))
department = str(input("Enter your Department: "))
cgpa = float(input("Enter your CGPA: "))
print("\nHey, " +str(name) ,"Here!")
print("My SID is "+str(sid))
print("I am from "+str(department),"Department and my CGPA is "+str(cgpa))
